<a href="https://colab.research.google.com/github/bhattrahul301/Assignment1/blob/main/Assignment1numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Create a null vector of size 10 but the fifth value which is 1.

import numpy as np

vector=np.zeros(10)
vector[4]=1
print(vector)

size=vector.size
print("The size of the vector is :","\n",size)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
The size of the vector is : 
 10


In [7]:
# Create a vector with values ranging from 10 to 49.
import numpy as np
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [12]:
# Create a 3x3 matrix with values ranging from 0 to 8

import numpy as np

matrix=np.arange(0,9).reshape(3,3)
print("The 3x3 matrix with values ranging from 0 to 8:","\n",matrix)

The 3x3 matrix with values ranging from 0 to 8: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np

Indices=np.array([1,2,0,0,4,0])
print("The original array is :","\n", Indices)

print("\nIndices of Non=Zero elements:")
Indices1 = np.nonzero(Indices == 0)
print(Indices1)

The original array is : 
 [1 2 0 0 4 0]

Indices of Non=Zero elements:
(array([2, 3, 5]),)


In [21]:
# Create a 10x10 array with random values and find the minimum and maximum values.

import numpy as np

array=np.random.rand(10,10)
print(array)

arraymin, arraymax = array.min(), array.max()
print("\nThe Minimum value in array is:","\n",arraymin)
print("The Maximum value in array is:","\n",arraymax)



[[0.4063157  0.55894821 0.17683269 0.048259   0.64186618 0.81581241
  0.4512146  0.70946263 0.55719668 0.83863966]
 [0.31650943 0.48105237 0.57829529 0.45950131 0.88720127 0.60940068
  0.69645809 0.36360105 0.39817251 0.32808808]
 [0.08478706 0.65916248 0.30465187 0.48283689 0.00920786 0.01852388
  0.47238878 0.77707948 0.83568197 0.83255336]
 [0.11874199 0.03659582 0.88874283 0.58998186 0.3943061  0.22367911
  0.73163578 0.30133475 0.01227272 0.99660751]
 [0.67053626 0.7644734  0.3501398  0.53887154 0.08981619 0.30986235
  0.04932436 0.89013766 0.83432009 0.03815161]
 [0.65592078 0.47056916 0.16734201 0.97728271 0.2407775  0.17273449
  0.2065506  0.66315904 0.8220683  0.36656565]
 [0.97925516 0.09862273 0.47958221 0.70291677 0.64462222 0.79655939
  0.02793545 0.88170899 0.39432577 0.80498885]
 [0.04535062 0.68032787 0.0917065  0.6690394  0.20805194 0.09060362
  0.6791114  0.63330441 0.60495966 0.92187158]
 [0.05974092 0.76532244 0.52799487 0.01743049 0.46611343 0.74671732
  0.04526308

In [25]:
# Create a random vector of size 30 and find the mean value.

import numpy as np

vector=np.random.rand(30)
print("\n The random vector of size 30 is :","\n", vector)

vector1=vector.mean()
print("\nThe Mean value of the randon vector is:","\n", vector1)


 The random vector of size 30 is : 
 [0.37515305 0.33572195 0.12108435 0.33868985 0.12747864 0.72273299
 0.70280273 0.76622622 0.36215319 0.21960046 0.38200807 0.48118245
 0.94516409 0.03418625 0.18596339 0.44468789 0.3513205  0.98825541
 0.09901545 0.70960704 0.56186171 0.75694572 0.17528259 0.55078162
 0.59513585 0.98251409 0.283743   0.26219394 0.90786198 0.35618564]

The Mean value of the randon vector is: 
 0.4708513368012346
